/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 24.04.2026 21:20:14

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 2128;
#else
constexpr int kTensorArenaSize = 1104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,54 } };
const TfArray<1, float> quant0_scale = { 1, { 0.13876916468143463, } };
const TfArray<1, int> quant0_zero = { 1, { 19 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 18, 3, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 18, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data3[2] = { -1, 144, };
const TfArray<1, int> tensor_dimension3 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data4[3] = { 152, 498, -1381, };
const TfArray<1, int> tensor_dimension4 = { 1, { 3 } };
const TfArray<1, float> quant4_scale = { 1, { 0.00021742474928032607, } };
const TfArray<1, int> quant4_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&quant4_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data5[3*20] = { 
  48, 20, 112, -79, 27, 41, 48, -31, -127, 68, 48, -45, 82, -124, 57, -26, -61, -114, 17, -18, 
  50, 48, -54, -82, -118, 14, 42, -123, 58, -69, -76, 61, -19, 62, -28, 61, 92, 102, -79, 3, 
  -89, -70, 14, 47, -84, -100, -102, -8, 52, 48, 95, -67, -117, 62, -32, 36, -59, -26, 36, 108, 
};
const TfArray<2, int> tensor_dimension5 = { 2, { 3,20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0069298860616981983, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant4_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[20] = { 582, 338, 237, -540, 285, 560, 558, -476, -1, -86, -397, -8, 440, -122, 206, -37, 42, 7, 6, -540, };
const TfArray<1, int> tensor_dimension6 = { 1, { 20 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00030264008091762662, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant4_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[20*144] = { 
  18, -25, 39, 27, 1, -3, 11, 21, -9, -36, 39, 11, -24, 46, -16, 9, -30, 55, -17, -5, 28, 7, 17, 3, 8, -19, 3, -17, -5, -46, 36, -22, -7, 10, -52, -18, 58, 16, 28, -36, -24, 1, 45, -28, 20, -11, -40, -19, -42, -23, -30, -43, 18, -57, -8, 38, 51, 7, 3, 1, -9, 127, 34, 4, 18, 41, -28, 23, -13, 26, -13, 34, -41, -13, 2, -47, -6, -11, 6, -9, -10, 37, -24, 16, 37, 18, -29, 10, 43, -29, 1, -11, 19, 24, 31, 38, 0, 9, -49, 12, -1, 0, -29, 43, -40, 32, -10, -31, -22, 47, 34, -36, 62, 29, 17, -14, -16, 30, -16, 24, -1, 23, -12, 11, -26, 25, -5, -44, -20, 14, 14, -4, -1, -28, -11, 34, 69, 22, 51, -10, 29, -4, 22, 7, 
  -5, 30, 31, -38, -20, -21, 25, 38, -20, -31, 14, -37, 42, -14, -10, 17, 17, 28, -10, -3, 29, -14, -18, 12, 27, -65, -6, -7, 8, 9, 14, 7, 17, 39, 11, -26, 57, -17, -23, -43, 30, 3, 32, -17, -3, 19, -24, 13, 30, -37, -39, -8, -19, -29, -19, 1, -41, -47, 6, 9, -2, 55, 23, -40, -17, -38, 0, 25, 30, 23, 33, 20, 10, -35, 1, 21, 51, 41, 4, -18, 39, 12, 4, 47, 44, -11, -32, 36, 14, 17, 42, -14, 48, 56, 6, 15, -5, 6, 22, 22, 4, 1, 43, 48, -23, 11, 13, -10, 38, -16, 11, -26, 8, 10, -7, -30, 22, 2, 4, -32, 18, -4, -36, -42, 13, -12, 20, -27, -10, -13, -21, -18, 26, -1, -5, 6, 5, -12, 27, 24, 31, -12, 34, 17, 
  -15, -20, -14, 3, -26, 27, -19, -2, 55, 7, -9, -29, 49, 1, -15, 18, -32, 8, -4, -5, 30, 63, 34, -15, 58, 21, 43, 42, -3, 34, -52, 21, -35, 39, -77, -69, 20, 36, -10, -11, 5, -21, 32, 34, -28, 6, 23, -36, 29, 11, -45, -9, -17, 12, 6, -14, -12, -27, 7, 29, 3, -4, 43, -23, -35, -5, -52, 0, -26, -20, -13, -26, 58, 21, -3, -23, -18, -39, -4, -4, -17, 37, -16, -47, -18, 40, -13, 17, -13, 15, 35, -9, -24, -3, 17, -24, -25, 26, -37, -22, -3, -39, -60, 4, 23, -39, -31, -12, -1, 10, -14, -31, -10, -28, -9, -26, -3, 43, 22, 11, -19, 21, -29, -31, 23, -17, -43, -52, -7, 46, -66, -46, 54, 37, 14, -24, 41, 20, -12, 13, -54, 3, -12, -25, 
  11, 27, -33, 3, -15, 41, -22, -20, -6, 44, 23, -16, -4, -17, -14, 39, 21, -18, -23, 41, -45, -2, -20, 26, -18, 36, -45, -9, -27, -7, -6, 51, -11, -38, 44, 17, -31, -14, -61, 11, 9, 15, 0, -2, 3, 15, 38, 80, -7, -5, -13, 22, -35, 40, 24, -31, -34, 46, -17, -16, -10, -41, 2, 52, 31, -24, -45, 27, 43, 38, -17, -37, 50, -32, 17, 23, -74, 19, 3, 80, 53, 27, 46, 10, -24, 20, -5, -45, -34, -16, 20, 1, -38, -106, -25, 17, -1, 35, 11, -49, 16, -57, -2, -27, -17, 20, -31, 28, 0, -51, -29, 45, -19, 9, 17, -1, -15, -4, -35, 9, 18, 34, 5, -23, -11, -34, 27, -11, 1, -7, -9, -38, -45, 15, 15, 18, -17, -19, 8, 11, -15, 14, -5, 50, 
  -21, -42, -12, 6, -32, 33, -23, -1, -5, 45, -13, 30, 10, 13, 0, 13, -52, 23, -36, -7, -29, 52, -6, 1, 63, 17, 32, -1, -19, 16, -8, -46, -32, -10, -35, 33, -12, 54, 55, 36, 2, 8, 9, 25, -45, 0, -25, -38, -14, -19, -17, 25, 53, -40, 2, -28, -4, -32, 36, -33, -24, 4, 9, 12, -41, 30, -9, -18, -27, 41, -22, -31, 47, 30, -7, -10, -8, -11, -35, -59, -95, -15, -64, 13, 50, 10, -7, -48, 49, 4, 4, 12, 1, -38, 21, -3, 45, 5, -20, 19, 25, 15, -24, 20, 15, -33, -44, -39, -31, 26, -3, 7, -11, 10, 52, -10, -27, -13, 25, 73, 35, 19, 18, 1, 5, 1, -33, 4, 41, -11, 14, -28, 12, 73, 14, -29, 10, 62, -2, 4, 8, -17, -17, -27, 
  -6, -15, 27, 14, -25, 14, -22, -11, -5, -9, -1, 23, 9, 28, 21, -29, -15, 25, -33, 1, 35, 5, -17, -19, 8, 55, -6, 26, 29, 18, 58, -41, 37, 33, -9, -28, 36, 12, 21, -12, -29, 0, -18, -18, 5, -5, -12, -37, -4, -9, -37, -25, 35, -43, -15, 7, -9, -26, 38, 18, -13, 32, 35, 25, -32, 10, 22, -28, -10, -4, -13, -6, -33, -10, 7, -36, -31, 6, 25, -60, -46, 16, -25, -4, 30, -5, -5, 16, 37, -32, 35, -11, -32, -12, 33, 17, 31, -10, 17, 44, -2, 41, -16, 48, 20, 32, -19, -23, -36, 32, 7, 12, -26, -30, 39, -18, 24, -32, 5, 1, 30, 11, 23, -16, 21, 2, 27, 9, 23, -3, -47, 1, 12, 9, 18, 18, 28, 38, -21, 16, -12, 23, -49, 9, 
  40, -15, 41, 3, 0, 11, -27, 4, 23, 0, 19, -6, 34, 6, -25, -30, -10, 43, -6, 15, 7, 38, 9, 12, -3, 39, 36, -1, -37, -22, 14, -45, 51, 49, -29, 8, 30, -40, 9, 4, 20, 8, 1, -63, -14, -37, -53, 3, 4, 14, -22, 3, 10, -55, -30, -7, 12, -63, -2, -10, -14, 105, 19, 1, -29, 45, -30, -6, -22, 9, -28, -2, 16, -1, 15, 14, 4, 22, 19, -37, -6, 4, -33, 16, 14, -46, -45, 11, 8, 28, 35, 19, -50, -9, 36, 4, 15, -16, -37, -18, -25, 29, 26, 23, -42, 44, -20, 10, 21, 38, 46, -20, 12, 3, 2, -35, 0, -14, 24, 29, 13, -40, -24, 16, -24, 26, -24, -39, -25, 39, -14, 43, 0, 0, 41, 51, -1, 33, 53, 11, -7, 16, 5, -38, 
  -18, 5, -13, 46, 26, -21, 25, -39, 28, 8, -14, -16, 0, -37, -29, 1, -2, -66, 0, 58, 9, 7, -46, -27, 5, -16, -25, -26, 23, -16, 31, 77, -8, -46, 52, 7, -52, 37, -30, 55, -9, 51, -70, 38, 36, 35, 21, 20, 42, 8, 10, 5, -9, -6, -2, -7, 8, 72, -28, 31, -6, -5, -7, 41, 33, -7, -16, -52, 58, 2, -1, -42, 69, 39, -3, 19, -65, -45, -35, 7, -1, -36, 27, 24, -45, 21, 35, 26, -28, 6, -12, 27, 3, -78, -33, 15, 42, -14, 6, -21, 41, 13, 3, -11, 44, 18, 13, -3, -35, -44, -12, -22, -24, 5, 2, 13, 27, -15, 25, 42, 0, 46, 41, 24, -34, -28, -3, 25, 55, 15, 7, 12, 17, 19, -12, 38, -65, 29, -54, -53, 24, 17, -62, -41, 
  39, 32, 27, -43, -9, 19, 20, -14, -25, -29, 5, 32, 25, 12, 30, -14, 43, -20, 13, -18, -25, -17, 19, 28, 8, -10, 3, -3, 20, 10, 14, 18, -12, 3, 86, 58, 41, -25, -61, -29, 18, -52, 34, -21, 22, 56, 20, 39, 9, -7, -40, -6, 25, 44, -19, -10, 16, -13, -23, 4, -18, -17, -4, 1, -16, -33, 16, 50, 38, 9, 19, -11, -5, -24, -22, -27, 26, -13, 11, 13, 34, -23, 79, 13, -34, -1, -17, -11, -18, 34, 26, -3, 5, -30, -35, 33, -21, 7, 27, -35, 30, 23, -30, 26, -35, -50, -43, -28, 10, 23, 29, 0, 37, -9, -36, 5, 6, 6, -13, 1, -32, 4, -12, 11, -19, 22, -36, -18, -11, 18, -15, 29, -4, -54, -22, -13, 19, -25, 23, -21, 22, 42, 26, 12, 
  19, -12, 34, 2, 27, -28, -24, 12, -6, 1, 35, -28, 3, -21, 14, 29, -39, -50, -1, 7, 22, -5, -50, -6, -16, 21, 26, 12, -34, -23, 22, 41, -6, -31, -57, -14, 8, 40, -17, 53, -14, 48, 8, -3, 3, 9, 6, 42, -29, -10, 6, 34, 31, -7, 14, 24, -9, 63, 25, 3, -25, -19, -33, 16, -2, 54, 1, -46, -12, 33, 16, 4, 7, 16, -9, -24, -53, -55, 13, 16, -1, -30, 21, -38, -31, -53, -22, 16, 43, 6, 11, -4, 21, -59, 33, 19, 29, -32, 10, 12, 20, -16, 32, 11, -6, 40, -1, -47, -14, -45, -17, -24, -15, 5, -40, 15, -24, 14, 16, -41, 11, 46, -14, 16, -67, -17, -16, -8, 8, -4, 40, -13, -17, 57, -33, 38, -11, 40, -1, -30, 30, -17, -53, -14, 
  -46, 0, -22, -13, -36, 1, 41, -43, -23, -1, -54, 15, 2, 14, 11, 44, -22, -46, 13, 3, -2, -22, -32, 21, 30, -5, 17, -15, -22, 31, 0, 58, 24, 1, 29, 39, -6, -11, -11, 25, -40, -2, -12, 7, 15, 14, 35, 7, 17, -19, 37, -10, -5, 17, 2, -13, 27, 68, -24, -22, 2, 1, -1, 31, 25, 15, -20, -44, 43, -21, -12, -59, 58, 27, -31, 3, -12, 1, -28, 50, 47, -10, 49, 26, -22, -26, 12, -1, -12, 15, 12, 42, -1, -74, -24, -13, 40, -7, 22, 10, -7, -15, 0, -32, 12, 6, -16, -28, 20, -15, -42, -11, -27, 24, -19, -6, -10, -12, 43, 33, 37, -19, 1, 36, -47, 8, -21, 29, 46, -42, 42, 22, -28, 12, -61, -18, -84, 44, -44, -17, 10, -13, 2, -12, 
  -54, 8, -19, -32, -2, -15, 6, 36, 8, -6, -27, 2, 13, -24, -14, -11, -49, -11, 5, -21, 17, 16, -2, -24, 14, 18, -10, -3, -10, -45, 0, 14, -12, 5, -5, -26, -25, -17, 32, -56, 32, -34, -10, -13, -27, -21, -8, 1, -13, -21, 18, -11, -52, 28, 15, 14, 2, 1, 20, -8, 2, 9, -9, 7, -43, -48, -27, -7, -33, 26, -37, 53, -29, 16, 27, 14, 7, -22, 15, -11, -30, -15, 24, -19, 1, -7, 18, 8, -3, 6, 18, 6, -9, 6, -8, 16, -2, 4, 4, 13, -25, -4, 37, 18, 9, -7, 15, 25, -7, 8, 5, -6, -23, -17, -44, 3, 33, 48, 29, 35, 19, 39, -26, -24, -4, 24, 15, 22, 27, -16, 16, 17, 15, 4, 7, -39, -20, -42, 11, 32, -38, -15, 0, -1, 
  -36, 8, 0, 19, -18, 27, -41, -11, -22, -3, 29, -54, -3, 37, 16, 19, -22, 23, -7, 4, -47, 42, 22, -35, 21, 8, 45, -13, -23, 3, -21, 0, -30, 51, -55, -3, -32, -13, 3, -22, -1, 10, -9, 14, -16, -29, -38, -44, -12, -12, 10, 16, 2, -13, 49, -26, 24, 5, 0, 9, -9, -12, 32, -40, -40, -1, -34, -57, -10, 49, 29, 10, -5, 41, 8, -22, 31, -21, -31, -71, -79, 17, -55, -40, 11, -45, 5, 4, 12, 12, -22, -7, -7, -28, -30, 1, -17, 34, 23, -31, 7, 5, -21, -1, -31, 6, 8, -7, -24, 29, 1, -16, 41, -31, 66, 11, -30, 24, -4, 14, 19, 10, 10, 14, -10, 43, -6, -18, -13, 19, 10, 32, 17, 58, 58, -1, 74, 50, 30, -15, -19, 35, -66, -21, 
  5, 13, 9, -18, 28, 8, -24, -17, -18, 13, 21, -1, -38, -2, 23, 28, 66, 16, 21, 10, 23, -21, 15, 35, -9, -16, 11, 23, -14, 18, 7, -13, -8, -28, 88, 22, 11, -28, -14, 19, -48, 31, 40, -34, 2, 46, -5, 50, 31, 12, -18, 10, 21, 35, -24, 19, -26, -1, 4, 20, 29, -38, -24, -3, -21, -32, 42, 28, 28, -40, -7, -30, -10, -13, -34, 39, 42, 0, 45, 25, 66, 37, 69, 15, 30, 48, 34, -17, -33, 50, 15, -25, 20, 26, 2, -20, 0, -32, 42, 1, -28, 21, 26, -21, -41, 15, -24, -27, -27, 0, 2, -28, -39, 24, -17, 27, 8, 9, -28, -34, -51, -38, 4, -38, -9, 13, 33, -16, -30, -14, -17, 16, -1, -24, -39, -28, 5, -22, -6, -31, 0, 14, 44, 60, 
  -7, -48, 16, 23, -3, 21, -12, -37, 28, 35, -12, -53, -20, 31, -45, 9, -25, 18, -51, -5, -42, 18, -33, 22, 20, 31, -16, 13, -2, -2, 14, 22, -49, 46, -88, 0, -7, -2, 33, 5, 13, -10, 10, 18, -49, -4, -45, -44, 14, 15, 5, -34, 25, -29, 8, -10, 19, 14, -18, -11, -19, 24, -6, -25, -15, 1, -7, -31, -17, 39, -33, -26, 44, 57, 36, 27, 7, 0, 13, -76, -108, 17, -63, -8, -21, 18, 3, 1, 1, -75, 16, 28, 5, 1, 19, -46, 0, 11, -18, 8, 23, 33, -36, 37, 33, -23, 10, 15, -16, 44, 36, -22, 23, 12, -2, -4, -10, 2, -6, 26, -28, 46, -18, 5, -22, 28, -7, -34, -15, 15, -11, -13, -11, 13, 42, 43, 74, 70, 40, 17, -10, -1, -63, -30, 
  19, 14, -49, 8, -19, 15, 18, -5, 5, -24, 19, -21, 11, -8, -18, 6, -1, 40, 12, 36, -3, -14, 26, -36, -20, -37, 24, -45, 1, 12, 22, -24, 19, 18, 36, 18, 31, 8, -28, -40, -27, 11, -3, -16, 47, 24, 19, 60, 23, 11, 5, -19, -14, 1, -18, -3, -36, 16, -23, 9, -22, -42, -10, -39, 32, -5, -7, 43, 16, 13, 10, 51, 20, -67, 1, 55, 63, 50, -15, 57, 57, 17, 59, 16, 20, 20, -2, 12, 12, 79, 18, -8, 50, 12, -46, 11, 15, 18, 3, 27, -30, 3, -9, 37, -29, 9, -32, 7, 52, -6, 19, 45, -6, -24, 16, -21, -9, -34, -8, -68, -11, 2, -8, 1, 13, 13, 39, -22, 2, -37, -9, 27, -47, -85, -39, 13, -37, -93, 26, 25, -42, -1, 55, 51, 
  25, -18, 30, -30, 5, 15, -5, 13, -8, -28, -6, -41, 9, 18, 45, -3, 25, 11, -7, -62, 43, -7, 3, -3, -52, -52, 17, -18, -41, 21, 10, -5, 17, -6, 10, 46, 17, -16, 1, -59, -14, -23, 36, -1, 38, 13, 27, 32, 20, 1, 8, 20, 4, 4, 2, -39, 2, -20, -30, -27, -17, 23, 15, -1, -33, -4, 41, 46, 32, -21, -12, 54, -50, -53, -23, 18, -2, 26, -25, -7, 56, -28, 43, -6, 15, 24, -15, -1, 7, 5, -41, -37, 56, 49, -14, -5, -4, 12, 43, 38, -29, -7, 28, -4, -3, -33, -13, -24, 11, 13, 38, -3, 9, 26, 47, 7, -18, -19, -44, -15, 15, -19, 3, -26, -34, 30, -15, -20, 30, 29, -16, -33, -10, -38, -6, 2, -50, -44, -5, 36, 21, -4, 73, -11, 
  25, 15, 18, -53, -21, 33, -4, 37, -7, 13, 10, -34, 20, 22, 7, -13, -10, -5, 18, -25, 20, -12, -25, -45, -30, -59, -28, -46, -25, 5, -5, 27, 1, -7, 14, 53, -33, -15, -22, 7, -34, -48, 12, -3, -9, 8, 6, 10, 39, 14, 23, -29, 16, 39, 29, 14, -49, 6, 0, -28, -40, 29, 0, -6, -6, -47, 11, 14, 20, 15, -29, 9, -49, -57, -9, 52, 46, 9, -1, -10, 23, 9, 43, 29, 5, -29, 8, 28, 7, 13, -24, -92, 50, 13, 18, 14, 29, -26, 17, -10, 14, -38, 39, 20, -3, 37, 35, 4, 47, 30, -1, 22, -6, -5, 54, 18, -6, -26, -8, -15, 30, -34, -34, -22, -15, 35, 6, 40, 27, 33, 40, -35, 12, 2, 17, -46, 27, -64, 8, 7, -25, -39, 3, 30, 
  -8, -9, -5, 12, -23, 22, -34, 29, 36, 20, -46, 24, -35, -41, -23, 57, -27, -35, 18, 56, -38, 6, -4, 41, 35, 72, -41, 17, 15, 35, 19, 13, -43, 20, 7, 23, -18, 55, 22, 74, 14, -4, -36, 5, -26, -6, 28, 3, 17, -13, -14, 5, 9, 23, 5, 7, -10, 47, 14, -33, -15, -47, 28, -19, 14, -26, -38, -25, 0, -11, -24, 2, 46, 47, 34, 11, -35, -41, 28, -23, -19, -12, 17, -2, 35, 29, 23, 2, 23, -24, -12, -32, -37, -63, -31, -48, 9, -7, 25, -3, 27, -27, -3, -21, 45, 18, -29, -1, -33, -4, -25, 36, 1, -7, -1, 38, 14, 60, -14, 55, -21, 27, 17, 13, -2, 6, -20, -13, -6, 30, -27, -17, -1, 12, 35, 18, 47, 69, 18, 43, 3, -35, -75, 30, 
  -58, -4, -21, 23, -57, 25, -10, -27, 31, 35, -78, 16, -38, -18, -45, -7, -11, 7, -16, 38, -10, -41, 22, 52, -2, 1, -22, 30, -28, 43, -32, 58, 5, -32, 35, 52, 10, 40, -37, 3, -43, 12, -24, 51, -36, 16, 41, 74, -21, -30, -4, 50, 2, 25, -27, -7, -19, 52, -55, -4, 38, -46, -11, 24, -35, -19, -1, 29, 14, -26, -12, -2, 48, -23, 31, 59, -32, -10, 8, 68, 43, 1, 89, -8, -19, 50, 14, -54, -48, 27, -18, 9, -34, -78, 20, 8, 2, 10, -17, 2, -27, -57, -17, -49, -17, -26, -14, 30, 22, -53, -17, 40, 13, 1, -13, 24, 27, 1, 3, 9, -44, 39, 16, 19, -16, 11, 11, 43, -17, 0, -3, -50, 17, -13, -19, 8, -8, 10, -34, -3, 9, -34, 29, 11, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 20,144 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0049167326651513577, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant4_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { 177, 572, 253, 39, 428, 219, 322, 116, 289, 99, 675, 69, 54, 456, 1, -93, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00057195028057321906, 0.00051016808720305562, 0.00046497848234139383, 0.00061664218083024025, 0.00040366090252064168, 0.00046015370753593743, 0.00040250795427709818, 0.00061977171571925282, 0.00049426947953179479, 0.00060431234305724502, 0.00037355851964093745, 0.00050665851449593902, 0.0004976373165845871, 0.00047779438318684697, 0.00060617568669840693, 0.00073002965655177832, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*3] = { 
  /* [0][0][][] */ -2,5,-104, 33,-65,54, 127,-56,-31, 
  /* [1][0][][] */ -89,-9,-90, -78,-15,-71, 83,127,-51, 
  /* [2][0][][] */ 76,-98,-127, 101,-21,104, 71,-56,-34, 
  /* [3][0][][] */ -43,-6,94, 75,99,-13, -24,-2,127, 
  /* [4][0][][] */ 114,-11,-46, 45,65,-87, 127,-13,-56, 
  /* [5][0][][] */ -26,-2,127, -32,0,-47, 12,-21,-115, 
  /* [6][0][][] */ 65,-39,-24, -94,-105,-62, -45,14,-127, 
  /* [7][0][][] */ 104,41,118, -28,6,127, 63,-47,-20, 
  /* [8][0][][] */ 19,29,-11, -75,11,-127, -62,29,-106, 
  /* [9][0][][] */ -60,70,127, 6,-13,-79, -81,55,-79, 
  /* [10][0][][] */ 113,-51,-90, 110,48,-102, -127,64,-77, 
  /* [11][0][][] */ -30,-74,-114, 70,-52,-127, 12,7,103, 
  /* [12][0][][] */ 35,110,35, 127,-26,74, 59,95,-41, 
  /* [13][0][][] */ 45,63,11, 61,127,119, 108,-40,64, 
  /* [14][0][][] */ 60,35,-17, -31,-64,-30, -55,-72,127, 
  /* [15][0][][] */ -17,29,48, 33,-34,-91, -40,17,127, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,3 } };
const TfArray<16, float> quant9_scale = { 16, { 0.004121595062315464, 0.003676379332318902, 0.0033507335465401411, 0.0044436543248593807, 0.0029088659211993217, 0.0033159651793539524, 0.0029005575925111771, 0.0044662063010036945, 0.003561810590326786, 0.0043548028916120529, 0.0026919418014585972, 0.0036510885693132877, 0.0035860799252986908, 0.0034430874511599541, 0.0043682302348315716, 0.0052607483230531216, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const TfArray<4, int> tensor_dimension10 = { 4, { 1,1,18,3 } };
const TfArray<4, int> tensor_dimension11 = { 4, { 1,1,18,16 } };
const TfArray<1, float> quant11_scale = { 1, { 0.061553087085485458, } };
const TfArray<1, int> quant11_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&quant11_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,18,1,16 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,9,1,16 } };
const TfArray<2, int> tensor_dimension14 = { 2, { 1,144 } };
const TfArray<2, int> tensor_dimension15 = { 2, { 1,20 } };
const TfArray<1, float> quant15_scale = { 1, { 0.031374938786029816, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension16 = { 2, { 1,3 } };
const TfArray<1, float> quant16_scale = { 1, { 0.12742644548416138, } };
const TfArray<1, int> quant16_zero = { 1, { -2 } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&quant16_zero, 0 };
const TfArray<1, float> quant17_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 10 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 10,9,8 } };
const TfArray<1, int> outputs1 = { 1, { 11 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 11,2 } };
const TfArray<1, int> outputs2 = { 1, { 12 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 12 } };
const TfArray<1, int> outputs3 = { 1, { 13 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 13,3 } };
const TfArray<1, int> outputs4 = { 1, { 14 } };
const TfLiteFullyConnectedParams opdata5 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs5 = { 3, { 14,7,6 } };
const TfArray<1, int> outputs5 = { 1, { 15 } };
const TfLiteFullyConnectedParams opdata6 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs6 = { 3, { 15,5,4 } };
const TfArray<1, int> outputs6 = { 1, { 16 } };
const TfLiteSoftmaxParams opdata7 = { 1 };
const TfArray<1, int> inputs7 = { 1, { 16 } };
const TfArray<1, int> outputs7 = { 1, { 17 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 54, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 2880, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension10, 54, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 288), (TfLiteIntArray*)&g0::tensor_dimension11, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 288), (TfLiteIntArray*)&g0::tensor_dimension13, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension15, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension16, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[8] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[8] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 18, };
const size_t tflNodes_subgraph_index[] = {0, 8, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  17, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_943975_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 18;
  for (size_t i = 0; i < 18; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_943975_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_943975_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_943975_5_invoke() {
  for (size_t i = 0; i < 8; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_943975_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
