/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_943975_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_943975_1[] = { "Correct", "Push", "Rest" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_943975_4_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
const uint32_t ei_dsp_config_943975_4_axes_size = 9;
ei_dsp_config_spectral_analysis_t ei_dsp_config_943975_4 = {
    4, // uint32_t blockId
    4, // int implementationVersion
    9, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    5.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_943975_4[54] = { 2.0663901849775317, 3.1217253602074253, 10.053884108929141, 2.438148270199386, 4.014560684252055, 1.692474924524914, 0.3997309764850137, 2.674962377562172, 7.336001940067471, 2.4320914569574636, 3.994606141312284, 0.20151700526011398, 0.7451081930830857, -0.18025112471523758, 1.9011740910363546, 2.423319359718584, 3.964489374958023, 0.2621913503793924, 2.7768403631347396, -0.9872752781114736, 2.8466604128404396, 2.405660947825115, 3.90442959098163, 1.6824857653348082, 6.44187885819117, 0.23296184203180065, 0.5751955777398811, 2.426422480891704, 3.9705208678346935, 1.5212637804417426, 1.8349163854144683, -0.6994545862738657, 2.0459720131290453, 2.429518771992747, 3.983069264971921, 1.0130900176399384, 6.083744368984886, 3.0650932797467774, 9.828337712077236, 2.438112925104131, 4.014405338557337, 2.7165266498398157, 3.116799387508588, -2.54889125695956, 8.105681190735497, 2.434222077287364, 4.001633382713252, 1.9934957630506258, 4.7448825647193935, 0.6458300555364301, 2.605595521591873, 2.432066581966814, 3.9933835848994836, 1.8585713558221666 };
const float ei_dn_standard_scaler_scale_943975_4[54] = { 2.0079893850436052, 0.8052242226515748, 4.036547913293355, 316.4749535378755, 102.04298308939211, 1.4181813993179964, 5.2319019395162805, 1.3042809057016609, 0.34332809603896436, 34.415700235218395, 10.690119744341269, 1.8383868344458285, 2.1461165418329133, 0.563391048289759, 0.20051759429987054, 17.20608457619836, 5.148289100541934, 1.2717513695555691, 0.7044525746147392, 0.6535521556300486, 0.23112883805296178, 10.691768897285733, 3.064352023875065, 2.818747753745812, 0.178410734021907, 1.0867874180385735, 0.4062291374174157, 11.567348868476271, 3.342367710512294, 0.7226858535916568, 0.7195297699579248, 0.7042414880479481, 0.26077149128074834, 15.263194143422716, 4.466592236708396, 1.7128348679483534, 1.0437600367774063, 0.7977082003404, 1.3799026432228387, 164.72347026158255, 52.93514865822237, 3.141693868059649, 0.5081267402460962, 0.6832435116697851, 0.41290765294632154, 42.87545607457963, 13.33737334803167, 1.986082478714559, 0.24020788723826728, 0.5592568437513109, 0.20694073880922517, 23.95189841877248, 7.333088734431226, 1.187637968907971 };
const float ei_dn_standard_scaler_var_943975_4[54] = { 0.24801455848656376, 1.5422910501171843, 0.061373342485155566, 0.000009984384799902154, 0.00009603592145016577, 0.4972060793695917, 0.03653261911628616, 0.5878380950365413, 8.483622002903953, 0.0008442805402883675, 0.008750540115729509, 0.29588721332533824, 0.2171167832497826, 3.150504582063297, 24.87110201703946, 0.003377815259563669, 0.037728900300429066, 0.6182947686876814, 2.015099422565447, 2.341205292048096, 18.71939153223934, 0.00874784086807793, 0.10649339961968604, 0.12585995546329243, 31.41651734561738, 0.846663419515561, 6.05979397157042, 0.0074736427129302166, 0.08951411985444724, 1.9147006857372582, 1.9315344816448352, 2.016307599516108, 14.705499433676483, 0.00429248852934924, 0.0501241921871248, 0.34085448235764654, 0.917906976374357, 1.5714909592170099, 0.5251738666830104, 0.00003685437358268504, 0.00035687138463853893, 0.10131465531391036, 3.873074932283702, 2.142145508781853, 5.865352738568563, 0.0005439794511326363, 0.005621592786260748, 0.2535160385129049, 17.33107386530885, 3.197255810350466, 23.351135799303638, 0.0017430912295679122, 0.018596281837112837, 0.7089765207245817 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_943975_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_943975_4,
    .mean_data_len = 54,
    .scale_data = (float *)ei_dn_standard_scaler_scale_943975_4,
    .scale_data_len = 54,
    .var_data = (float *)ei_dn_standard_scaler_var_943975_4,
    .var_data_len = 54
};
ei_data_normalization_t ei_data_normalization_config_943975_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_943975_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_943975_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_943975_1[ei_dsp_blocks_943975_1_size] = {
    { // DSP block 4
        4,
        54, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_943975_4, // pointer to config struct
        ei_dsp_config_943975_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_943975_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_943975_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_943975_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_943975_5_init,
    .model_invoke = &tflite_learn_943975_5_invoke,
    .model_reset = &tflite_learn_943975_5_reset,
    .model_input = &tflite_learn_943975_5_input,
    .model_output = &tflite_learn_943975_5_output,
};

const uint8_t ei_output_tensors_indices_943975_5[1] = { 0 };
const uint8_t ei_output_tensors_size_943975_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_943975_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_943975_5,
    .output_tensors_size = ei_output_tensors_size_943975_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_943975_5,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_943975_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .anom_axis = ei_classifier_anom_axes_943975_6,
    .anom_axes_size = 18,
    .anom_clusters = ei_classifier_anom_clusters_943975_6,
    .anom_cluster_count = 64,
    .anom_scale = ei_classifier_anom_scale_943975_6,
    .anom_mean = ei_classifier_anom_mean_943975_6,
};

const uint8_t ei_learning_blocks_943975_1_size = 2;
const uint32_t ei_learning_block_943975_5_inputs[1] = { 4 };
const uint8_t ei_learning_block_943975_5_inputs_size = 1;
const uint32_t ei_learning_block_943975_6_inputs[1] = { 4 };
const uint8_t ei_learning_block_943975_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_943975_1[ei_learning_blocks_943975_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_943975_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_943975_5_inputs,
        ei_learning_block_943975_5_inputs_size,
    },
    {
        6,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_943975_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_943975_6_inputs,
        ei_learning_block_943975_6_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_943975_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_943975_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_943975_1[ei_postprocessing_blocks_943975_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_943975_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_943975_1_size = 0;

uint32_t *freeform_outputs_943975_1 = nullptr;

const ei_impulse_t impulse_943975_1 = {
    .project_id = 943975,
    .project_owner = "harshakvaliyamannil",
    .project_name = "Lume PFM Rehab Monitor",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 54,
    .raw_sample_count = 200,
    .raw_samples_per_frame = 9,
    .dsp_input_frame_size = 200 * 9,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,

    .dsp_blocks_size = ei_dsp_blocks_943975_1_size,
    .dsp_blocks = ei_dsp_blocks_943975_1,

    .learning_blocks_size = ei_learning_blocks_943975_1_size,
    .learning_blocks = ei_learning_blocks_943975_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_943975_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_943975_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "accX + accY + accZ + gyrX + gyrY + gyrZ + magX + magY + magZ",
    .slice_size = (200/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_943975_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_943975_1_size,
    .freeform_outputs = freeform_outputs_943975_1
};

ei_impulse_handle_t impulse_handle_943975_1 = ei_impulse_handle_t( &impulse_943975_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_943975_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_943975_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_943975_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_943975_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
